DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'app_user') THEN
    CREATE ROLE app_user LOGIN PASSWORD 'app_password';
  END IF;
END $$;

CREATE SCHEMA IF NOT EXISTS app_data AUTHORIZATION app_user;

CREATE TABLE IF NOT EXISTS app_data.users (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(255) UNIQUE NOT NULL
);

ALTER TABLE app_data.users OWNER TO app_user;
ALTER SEQUENCE IF EXISTS app_data.users_id_seq OWNER TO app_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA app_data TO app_user;

GRANT USAGE ON SCHEMA app_data TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA app_data TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA app_data
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA app_data
  GRANT USAGE, SELECT ON SEQUENCES TO app_user;
