CREATE ROLE app_user WITH LOGIN PASSWORD 'app_password';

CREATE SCHEMA IF NOT EXISTS app_data AUTHORIZATION app_user;

GRANT ALL PRIVILEGES ON DATABASE task4db TO app_user;
GRANT ALL ON SCHEMA app_data TO app_user;
