spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task4db
    username: app_user
    password: app_password

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
