spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/task4db
    username: app_user
    password: app_password
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate.format_sql: true

  flyway:
    enabled: true
    schemas: app_data
    locations: classpath:db/migration

logging:
  level:
    org.hibernate.SQL: debug
